### ISSUE TITLE
Potentially move file to /docker-entrypoint.d/

### ISSUE THREAD

**Issue by tomw1808** [maximemoreillon/vue-runtime-env#1]
I think the approach you take is amazing, and I am very grateful I stumbled upon it.

However, since a few versions of nginx, there is actually a /docker-entrypoint.d/ which runs files before starting nginx. So, you could, potentially just move the search/replace operation into a shell script without compromising the rest of the entrypoint in nginx.

**Comment by maximemoreillon** [comment]
Thank you very much for your feedback! Just to be transparent, the idea is definitely not mine. I found it on StackOverflow [here](https://stackoverflow.com/a/57928031)

I didn't know about the /docker-entrypoint.d . I tried moving the script in there and it worked!  Thus, I updated this repository accordingly

If you agree with my modifications, feel free to close the issue.

Thanks !
