### ISSUE TITLE
dockerfile report error

### ISSUE THREAD

**Issue by yashualaoda** [maximemoreillon/vue-runtime-env#2]
when i run the docker image command，it show me error message： unknown instruction: exec.
![image](https://github.com/maximemoreillon/vue-runtime-env/assets/36359551/39d6e69c-fa44-42fb-a327-6500c82e3d61)
how  to repaire this problem?
best wishes

**Comment by maximemoreillon** [comment]
Hello!

Thanks a lot for your issue.

Sorry it was a mistake of mine, exec "$@" is was supposed to go in substitute_environment_variables.sh

I fixed it in https://github.com/maximemoreillon/vue-runtime-env/commit/aaa95bd2d304217b4a270ecaa364d28a850422b7
